export const APPLE_SET_VALUES = 'APPLE_SET_VALUES';
export const SPOTIFY_SET_VALUES = 'SPOTIFY_SET_VALUES';
export const USER_SET_VALUES = 'USER_SET_VALUES';
export const APP_SET_VALUES = 'APP_SET_VALUES';
export const APP_RESET = 'APP_RESET';
export const BROADCASTERS_SET = 'BROADCASTERS_SET';